# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'firms.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1179, 480)
        self.tableWidget_5 = QTableWidget(Dialog)
        if (self.tableWidget_5.columnCount() < 15):
            self.tableWidget_5.setColumnCount(15)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(9, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(10, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(11, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(12, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(13, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(14, __qtablewidgetitem14)
        self.tableWidget_5.setObjectName(u"tableWidget_5")
        self.tableWidget_5.setGeometry(QRect(470, 80, 691, 331))
        self.tableWidget_5.setFrameShape(QFrame.WinPanel)
        self.tableWidget_5.setFrameShadow(QFrame.Sunken)
        self.tableWidget_5.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_5.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_5.setAlternatingRowColors(True)
        self.tableWidget_5.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_5.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_5.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(97)
        self.tableWidget_5.verticalHeader().setCascadingSectionResizes(True)
        self.groupBox_15 = QGroupBox(Dialog)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 10, 421, 401))
        self.label_54 = QLabel(self.groupBox_15)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(-1, 30, 51, 30))
        self.label_54.setMidLineWidth(0)
        self.label_54.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_55 = QLabel(self.groupBox_15)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(19, 150, 51, 30))
        self.label_55.setMidLineWidth(0)
        self.label_55.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_39 = QLineEdit(self.groupBox_15)
        self.lineEdit_39.setObjectName(u"lineEdit_39")
        self.lineEdit_39.setGeometry(QRect(70, 110, 341, 31))
        self.label_56 = QLabel(self.groupBox_15)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(230, 150, 51, 30))
        self.label_56.setMidLineWidth(0)
        self.label_56.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_45 = QLineEdit(self.groupBox_15)
        self.lineEdit_45.setObjectName(u"lineEdit_45")
        self.lineEdit_45.setGeometry(QRect(70, 30, 91, 31))
        self.lineEdit_45.setReadOnly(False)
        self.lineEdit_45.setClearButtonEnabled(False)
        self.label_57 = QLabel(self.groupBox_15)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(0, 110, 61, 30))
        self.label_57.setMidLineWidth(0)
        self.label_57.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_46 = QLineEdit(self.groupBox_15)
        self.lineEdit_46.setObjectName(u"lineEdit_46")
        self.lineEdit_46.setGeometry(QRect(90, 150, 111, 31))
        self.lineEdit_47 = QLineEdit(self.groupBox_15)
        self.lineEdit_47.setObjectName(u"lineEdit_47")
        self.lineEdit_47.setGeometry(QRect(301, 150, 111, 31))
        self.lineEdit_48 = QLineEdit(self.groupBox_15)
        self.lineEdit_48.setObjectName(u"lineEdit_48")
        self.lineEdit_48.setGeometry(QRect(280, 230, 131, 31))
        self.label_58 = QLabel(self.groupBox_15)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(130, 230, 130, 30))
        self.label_58.setMidLineWidth(0)
        self.label_58.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_49 = QLineEdit(self.groupBox_15)
        self.lineEdit_49.setObjectName(u"lineEdit_49")
        self.lineEdit_49.setGeometry(QRect(280, 270, 131, 31))
        self.label_59 = QLabel(self.groupBox_15)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(130, 270, 130, 30))
        self.label_59.setMidLineWidth(0)
        self.label_59.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_60 = QLabel(self.groupBox_15)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(230, 30, 71, 30))
        self.label_60.setMidLineWidth(0)
        self.label_60.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_50 = QLineEdit(self.groupBox_15)
        self.lineEdit_50.setObjectName(u"lineEdit_50")
        self.lineEdit_50.setGeometry(QRect(310, 30, 101, 31))
        self.lineEdit_50.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.label_61 = QLabel(self.groupBox_15)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(9, 190, 61, 30))
        self.label_61.setMidLineWidth(0)
        self.label_61.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_51 = QLineEdit(self.groupBox_15)
        self.lineEdit_51.setObjectName(u"lineEdit_51")
        self.lineEdit_51.setGeometry(QRect(90, 190, 321, 31))
        self.lineEdit_51.setInputMethodHints(Qt.ImhFormattedNumbersOnly)
        self.lineEdit_54 = QLineEdit(self.groupBox_15)
        self.lineEdit_54.setObjectName(u"lineEdit_54")
        self.lineEdit_54.setGeometry(QRect(280, 310, 131, 31))
        self.label_65 = QLabel(self.groupBox_15)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(130, 310, 130, 30))
        self.label_65.setMidLineWidth(0)
        self.label_65.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_66 = QLabel(self.groupBox_15)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(0, 70, 61, 30))
        self.label_66.setMidLineWidth(0)
        self.label_66.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_55 = QLineEdit(self.groupBox_15)
        self.lineEdit_55.setObjectName(u"lineEdit_55")
        self.lineEdit_55.setGeometry(QRect(70, 70, 341, 31))
        self.label_62 = QLabel(self.groupBox_15)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(10, 310, 31, 30))
        self.label_62.setMidLineWidth(0)
        self.label_62.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_64 = QLabel(self.groupBox_15)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(10, 270, 31, 30))
        self.label_64.setMidLineWidth(0)
        self.label_64.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_52 = QLineEdit(self.groupBox_15)
        self.lineEdit_52.setObjectName(u"lineEdit_52")
        self.lineEdit_52.setGeometry(QRect(60, 310, 101, 31))
        self.lineEdit_53 = QLineEdit(self.groupBox_15)
        self.lineEdit_53.setObjectName(u"lineEdit_53")
        self.lineEdit_53.setGeometry(QRect(60, 270, 101, 31))
        self.textEdit_4 = QTextEdit(self.groupBox_15)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(20, 350, 381, 41))
        self.groupBox_25 = QGroupBox(Dialog)
        self.groupBox_25.setObjectName(u"groupBox_25")
        self.groupBox_25.setGeometry(QRect(470, 0, 601, 80))
        self.lineEdit_76 = QLineEdit(self.groupBox_25)
        self.lineEdit_76.setObjectName(u"lineEdit_76")
        self.lineEdit_76.setGeometry(QRect(70, 40, 281, 30))
        self.pushButton_22 = QPushButton(self.groupBox_25)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(510, 40, 80, 30))
        self.comboBox_10 = QComboBox(self.groupBox_25)
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.setObjectName(u"comboBox_10")
        self.comboBox_10.setGeometry(QRect(380, 40, 121, 30))
        self.label_30 = QLabel(self.groupBox_25)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 40, 55, 30))
        self.label_30.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(50, 430, 80, 25))
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(140, 430, 80, 25))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        ___qtablewidgetitem = self.tableWidget_5.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"id", None));
        ___qtablewidgetitem1 = self.tableWidget_5.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"Cari Kod", None));
        ___qtablewidgetitem2 = self.tableWidget_5.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"Ad", None));
        ___qtablewidgetitem3 = self.tableWidget_5.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Dialog", u"Adress", None));
        ___qtablewidgetitem4 = self.tableWidget_5.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Dialog", u"\u015eehir", None));
        ___qtablewidgetitem5 = self.tableWidget_5.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Dialog", u"\u0130l\u00e7e", None));
        ___qtablewidgetitem6 = self.tableWidget_5.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Dialog", u"Telefon", None));
        ___qtablewidgetitem7 = self.tableWidget_5.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Dialog", u"Fax", None));
        ___qtablewidgetitem8 = self.tableWidget_5.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Dialog", u"Web", None));
        ___qtablewidgetitem9 = self.tableWidget_5.horizontalHeaderItem(9)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Dialog", u"Sektor_kod", None));
        ___qtablewidgetitem10 = self.tableWidget_5.horizontalHeaderItem(10)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("Dialog", u"Sektor", None));
        ___qtablewidgetitem11 = self.tableWidget_5.horizontalHeaderItem(11)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("Dialog", u"IK Ad\u0131", None));
        ___qtablewidgetitem12 = self.tableWidget_5.horizontalHeaderItem(12)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("Dialog", u"IK Telefon", None));
        ___qtablewidgetitem13 = self.tableWidget_5.horizontalHeaderItem(13)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("Dialog", u"IK email", None));
        ___qtablewidgetitem14 = self.tableWidget_5.horizontalHeaderItem(14)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("Dialog", u"Notlar", None));
        self.groupBox_15.setTitle(QCoreApplication.translate("Dialog", u"Firma Bilgileri", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"Cari Kod", None))
        self.label_55.setText(QCoreApplication.translate("Dialog", u"Telefon", None))
        self.lineEdit_39.setText("")
        self.lineEdit_39.setPlaceholderText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"Fax", None))
        self.lineEdit_45.setText("")
        self.lineEdit_45.setPlaceholderText(QCoreApplication.translate("Dialog", u"Cari Kod", None))
        self.label_57.setText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.lineEdit_46.setText("")
        self.lineEdit_46.setPlaceholderText(QCoreApplication.translate("Dialog", u"Telefon", None))
        self.lineEdit_47.setText("")
        self.lineEdit_47.setPlaceholderText(QCoreApplication.translate("Dialog", u"Fax", None))
        self.lineEdit_48.setText("")
        self.lineEdit_48.setPlaceholderText(QCoreApplication.translate("Dialog", u"IK Ad ve Soyad", None))
        self.label_58.setText(QCoreApplication.translate("Dialog", u"IK Ad\u0131 ve Soyad\u0131", None))
        self.lineEdit_49.setText("")
        self.lineEdit_49.setPlaceholderText(QCoreApplication.translate("Dialog", u"Veli Telefon", None))
        self.label_59.setText(QCoreApplication.translate("Dialog", u"IK Telefon", None))
        self.label_60.setText(QCoreApplication.translate("Dialog", u"Melsek Kod", None))
        self.lineEdit_50.setPlaceholderText(QCoreApplication.translate("Dialog", u"Meslek Kod", None))
        self.label_61.setText(QCoreApplication.translate("Dialog", u"Web adres", None))
        self.lineEdit_51.setPlaceholderText(QCoreApplication.translate("Dialog", u"web adres", None))
        self.lineEdit_54.setText("")
        self.lineEdit_54.setPlaceholderText(QCoreApplication.translate("Dialog", u"IK email", None))
        self.label_65.setText(QCoreApplication.translate("Dialog", u"IK email", None))
        self.label_66.setText(QCoreApplication.translate("Dialog", u"Meslek ", None))
        self.lineEdit_55.setText("")
        self.lineEdit_55.setPlaceholderText(QCoreApplication.translate("Dialog", u"Meslek a\u00e7\u0131klama", None))
        self.label_62.setText(QCoreApplication.translate("Dialog", u"\u0130l\u00e7e", None))
        self.label_64.setText(QCoreApplication.translate("Dialog", u"\u015eehir", None))
        self.lineEdit_52.setPlaceholderText(QCoreApplication.translate("Dialog", u"il\u00e7e Ad\u0131", None))
        self.lineEdit_53.setPlaceholderText(QCoreApplication.translate("Dialog", u"\u015eehir Ad\u0131", None))
        self.textEdit_4.setPlaceholderText(QCoreApplication.translate("Dialog", u"Adres B\u0130lgileri", None))
        self.groupBox_25.setTitle(QCoreApplication.translate("Dialog", u"Filitre", None))
        self.pushButton_22.setText(QCoreApplication.translate("Dialog", u"Sorgula", None))
        self.comboBox_10.setItemText(0, QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.comboBox_10.setItemText(1, QCoreApplication.translate("Dialog", u"Cari Kod", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("Dialog", u"Adres", None))

        self.label_30.setText(QCoreApplication.translate("Dialog", u"Deger", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"OK", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Iptal", None))
    # retranslateUi

