# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'internship.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1288, 706)
        self.tableWidget_7 = QTableWidget(Dialog)
        if (self.tableWidget_7.columnCount() < 7):
            self.tableWidget_7.setColumnCount(7)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        self.tableWidget_7.setObjectName(u"tableWidget_7")
        self.tableWidget_7.setGeometry(QRect(10, 300, 1271, 391))
        self.tableWidget_7.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_7.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_7.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_7.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_7.setSortingEnabled(True)
        self.tableWidget_7.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_7.horizontalHeader().setDefaultSectionSize(85)
        self.tableWidget_7.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableWidget_7.horizontalHeader().setStretchLastSection(True)
        self.groupBox_27 = QGroupBox(Dialog)
        self.groupBox_27.setObjectName(u"groupBox_27")
        self.groupBox_27.setGeometry(QRect(1050, 60, 211, 131))
        self.pushButton_2 = QPushButton(self.groupBox_27)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(110, 50, 91, 50))
        self.pushButton = QPushButton(self.groupBox_27)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 50, 91, 50))
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 220, 1261, 70))
        self.comboBox_14 = QComboBox(self.groupBox_2)
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.setObjectName(u"comboBox_14")
        self.comboBox_14.setGeometry(QRect(905, 27, 71, 31))
        self.lineEdit = QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(120, 27, 231, 30))
        self.comboBox_12 = QComboBox(self.groupBox_2)
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.setObjectName(u"comboBox_12")
        self.comboBox_12.setGeometry(QRect(620, 27, 201, 31))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(9, 27, 111, 30))
        self.label_96 = QLabel(self.groupBox_2)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(830, 27, 70, 30))
        self.label_96.setMidLineWidth(0)
        self.label_96.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_79 = QLabel(self.groupBox_2)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(550, 28, 61, 30))
        self.label_79.setMidLineWidth(0)
        self.label_79.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox = QComboBox(self.groupBox_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(380, 30, 150, 30))
        self.pushButton_3 = QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(1020, 27, 93, 30))
        self.groupBox_37 = QGroupBox(Dialog)
        self.groupBox_37.setObjectName(u"groupBox_37")
        self.groupBox_37.setGeometry(QRect(10, 10, 131, 211))
        self.label_152 = QLabel(self.groupBox_37)
        self.label_152.setObjectName(u"label_152")
        self.label_152.setGeometry(QRect(10, 30, 111, 171))
        self.label_152.setFrameShape(QFrame.WinPanel)
        self.label_152.setIndent(0)
        self.groupBox_35 = QGroupBox(Dialog)
        self.groupBox_35.setObjectName(u"groupBox_35")
        self.groupBox_35.setGeometry(QRect(370, 10, 421, 211))
        self.lineEdit_95 = QLineEdit(self.groupBox_35)
        self.lineEdit_95.setObjectName(u"lineEdit_95")
        self.lineEdit_95.setEnabled(False)
        self.lineEdit_95.setGeometry(QRect(70, 70, 341, 31))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush1 = QBrush(QColor(0, 0, 0, 128))
        brush1.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_95.setPalette(palette)
        self.label_146 = QLabel(self.groupBox_35)
        self.label_146.setObjectName(u"label_146")
        self.label_146.setGeometry(QRect(2, 70, 61, 30))
        self.label_146.setMidLineWidth(0)
        self.label_146.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_98 = QLineEdit(self.groupBox_35)
        self.lineEdit_98.setObjectName(u"lineEdit_98")
        self.lineEdit_98.setEnabled(False)
        self.lineEdit_98.setGeometry(QRect(90, 110, 121, 31))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_98.setPalette(palette1)
        self.label_149 = QLabel(self.groupBox_35)
        self.label_149.setObjectName(u"label_149")
        self.label_149.setGeometry(QRect(2, 110, 81, 30))
        self.label_149.setMidLineWidth(0)
        self.label_149.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_151 = QLabel(self.groupBox_35)
        self.label_151.setObjectName(u"label_151")
        self.label_151.setGeometry(QRect(0, 150, 81, 30))
        self.label_151.setMidLineWidth(0)
        self.label_151.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_99 = QLineEdit(self.groupBox_35)
        self.lineEdit_99.setObjectName(u"lineEdit_99")
        self.lineEdit_99.setEnabled(False)
        self.lineEdit_99.setGeometry(QRect(90, 150, 201, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_99.setPalette(palette2)
        self.label_150 = QLabel(self.groupBox_35)
        self.label_150.setObjectName(u"label_150")
        self.label_150.setEnabled(True)
        self.label_150.setGeometry(QRect(240, 20, 91, 30))
        self.label_150.setMidLineWidth(0)
        self.label_150.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_36 = QLineEdit(self.groupBox_35)
        self.lineEdit_36.setObjectName(u"lineEdit_36")
        self.lineEdit_36.setEnabled(False)
        self.lineEdit_36.setGeometry(QRect(340, 20, 71, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_36.setPalette(palette3)
        self.groupBox_38 = QGroupBox(Dialog)
        self.groupBox_38.setObjectName(u"groupBox_38")
        self.groupBox_38.setGeometry(QRect(150, 10, 221, 211))
        self.label_153 = QLabel(self.groupBox_38)
        self.label_153.setObjectName(u"label_153")
        self.label_153.setGeometry(QRect(29, 30, 21, 29))
        self.label_153.setMidLineWidth(0)
        self.label_153.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_103 = QLineEdit(self.groupBox_38)
        self.lineEdit_103.setObjectName(u"lineEdit_103")
        self.lineEdit_103.setEnabled(False)
        self.lineEdit_103.setGeometry(QRect(71, 64, 131, 30))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_103.setPalette(palette4)
        self.lineEdit_103.setMaxLength(20)
        self.lineEdit_104 = QLineEdit(self.groupBox_38)
        self.lineEdit_104.setObjectName(u"lineEdit_104")
        self.lineEdit_104.setEnabled(False)
        self.lineEdit_104.setGeometry(QRect(70, 30, 131, 30))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_104.setPalette(palette5)
        self.lineEdit_104.setMaxLength(30)
        self.lineEdit_104.setReadOnly(False)
        self.lineEdit_104.setClearButtonEnabled(False)
        self.label_154 = QLabel(self.groupBox_38)
        self.label_154.setObjectName(u"label_154")
        self.label_154.setGeometry(QRect(10, 64, 41, 29))
        self.label_154.setMidLineWidth(0)
        self.label_154.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_155 = QLabel(self.groupBox_38)
        self.label_155.setObjectName(u"label_155")
        self.label_155.setGeometry(QRect(40, 102, 51, 29))
        self.label_155.setMidLineWidth(0)
        self.label_155.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_105 = QLineEdit(self.groupBox_38)
        self.lineEdit_105.setObjectName(u"lineEdit_105")
        self.lineEdit_105.setEnabled(False)
        self.lineEdit_105.setGeometry(QRect(100, 102, 71, 30))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_105.setPalette(palette6)
        self.lineEdit_105.setMaxLength(5)
        self.lineEdit_106 = QLineEdit(self.groupBox_38)
        self.lineEdit_106.setObjectName(u"lineEdit_106")
        self.lineEdit_106.setEnabled(False)
        self.lineEdit_106.setGeometry(QRect(100, 135, 71, 30))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_106.setPalette(palette7)
        self.lineEdit_106.setMaxLength(4)
        self.lineEdit_106.setEchoMode(QLineEdit.Normal)
        self.lineEdit_106.setReadOnly(False)
        self.label_156 = QLabel(self.groupBox_38)
        self.label_156.setObjectName(u"label_156")
        self.label_156.setGeometry(QRect(39, 135, 51, 29))
        self.label_156.setMidLineWidth(0)
        self.label_156.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_157 = QLabel(self.groupBox_38)
        self.label_157.setObjectName(u"label_157")
        self.label_157.setGeometry(QRect(130, 170, 21, 30))
        self.label_157.setMidLineWidth(0)
        self.label_157.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_107 = QLineEdit(self.groupBox_38)
        self.lineEdit_107.setObjectName(u"lineEdit_107")
        self.lineEdit_107.setEnabled(False)
        self.lineEdit_107.setGeometry(QRect(100, 170, 41, 30))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_107.setPalette(palette8)
        self.lineEdit_107.setEchoMode(QLineEdit.Normal)
        self.lineEdit_107.setReadOnly(False)
        self.lineEdit_108 = QLineEdit(self.groupBox_38)
        self.lineEdit_108.setObjectName(u"lineEdit_108")
        self.lineEdit_108.setEnabled(False)
        self.lineEdit_108.setGeometry(QRect(150, 170, 41, 30))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_108.setPalette(palette9)
        self.lineEdit_108.setEchoMode(QLineEdit.Normal)
        self.lineEdit_108.setReadOnly(False)
        self.label_158 = QLabel(self.groupBox_38)
        self.label_158.setObjectName(u"label_158")
        self.label_158.setGeometry(QRect(50, 170, 41, 30))
        self.label_158.setMidLineWidth(0)
        self.label_158.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.textEdit_10 = QTextEdit(Dialog)
        self.textEdit_10.setObjectName(u"textEdit_10")
        self.textEdit_10.setEnabled(False)
        self.textEdit_10.setGeometry(QRect(800, 20, 211, 201))
        self.textEdit_10.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.textEdit_10.setAutoFormatting(QTextEdit.AutoBulletList)
        self.textEdit_10.setTabChangesFocus(True)
        self.textEdit_10.setOverwriteMode(False)
        QWidget.setTabOrder(self.lineEdit, self.comboBox)
        QWidget.setTabOrder(self.comboBox, self.comboBox_12)
        QWidget.setTabOrder(self.comboBox_12, self.comboBox_14)
        QWidget.setTabOrder(self.comboBox_14, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.pushButton)
        QWidget.setTabOrder(self.pushButton, self.pushButton_2)
        QWidget.setTabOrder(self.pushButton_2, self.textEdit_10)
        QWidget.setTabOrder(self.textEdit_10, self.tableWidget_7)
        QWidget.setTabOrder(self.tableWidget_7, self.lineEdit_95)
        QWidget.setTabOrder(self.lineEdit_95, self.lineEdit_98)
        QWidget.setTabOrder(self.lineEdit_98, self.lineEdit_99)
        QWidget.setTabOrder(self.lineEdit_99, self.lineEdit_36)
        QWidget.setTabOrder(self.lineEdit_36, self.lineEdit_103)
        QWidget.setTabOrder(self.lineEdit_103, self.lineEdit_104)
        QWidget.setTabOrder(self.lineEdit_104, self.lineEdit_105)
        QWidget.setTabOrder(self.lineEdit_105, self.lineEdit_106)
        QWidget.setTabOrder(self.lineEdit_106, self.lineEdit_107)
        QWidget.setTabOrder(self.lineEdit_107, self.lineEdit_108)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        ___qtablewidgetitem = self.tableWidget_7.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"Kay\u0131t No", None));
        ___qtablewidgetitem1 = self.tableWidget_7.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"Donem", None));
        ___qtablewidgetitem2 = self.tableWidget_7.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"Staj Turu", None));
        ___qtablewidgetitem3 = self.tableWidget_7.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None));
        ___qtablewidgetitem4 = self.tableWidget_7.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Dialog", u"\u00d6\u011frenci Ad\u0131", None));
        ___qtablewidgetitem5 = self.tableWidget_7.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Dialog", u"\u00d6\u011frenci Soyad\u0131", None));
        ___qtablewidgetitem6 = self.tableWidget_7.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Dialog", u"Ac\u0131klama", None));
        self.groupBox_27.setTitle(QCoreApplication.translate("Dialog", u"Kontrol", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"IPTAL", None))
#if QT_CONFIG(shortcut)
        self.pushButton_2.setShortcut(QCoreApplication.translate("Dialog", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"SE\u00c7", None))
#if QT_CONFIG(shortcut)
        self.pushButton.setShortcut(QCoreApplication.translate("Dialog", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Filitre", None))
        self.comboBox_14.setItemText(0, QCoreApplication.translate("Dialog", u"2020", None))
        self.comboBox_14.setItemText(1, QCoreApplication.translate("Dialog", u"2021", None))
        self.comboBox_14.setItemText(2, QCoreApplication.translate("Dialog", u"2022", None))
        self.comboBox_14.setItemText(3, QCoreApplication.translate("Dialog", u"2023", None))
        self.comboBox_14.setItemText(4, QCoreApplication.translate("Dialog", u"2024", None))
        self.comboBox_14.setItemText(5, QCoreApplication.translate("Dialog", u"2025", None))
        self.comboBox_14.setItemText(6, QCoreApplication.translate("Dialog", u"2026", None))
        self.comboBox_14.setItemText(7, QCoreApplication.translate("Dialog", u"2027", None))
        self.comboBox_14.setItemText(8, QCoreApplication.translate("Dialog", u"2028", None))
        self.comboBox_14.setItemText(9, QCoreApplication.translate("Dialog", u"2029", None))
        self.comboBox_14.setItemText(10, QCoreApplication.translate("Dialog", u"2030", None))
        self.comboBox_14.setItemText(11, QCoreApplication.translate("Dialog", u"2031", None))
        self.comboBox_14.setItemText(12, QCoreApplication.translate("Dialog", u"2032", None))
        self.comboBox_14.setItemText(13, QCoreApplication.translate("Dialog", u"2033", None))
        self.comboBox_14.setItemText(14, QCoreApplication.translate("Dialog", u"2034", None))
        self.comboBox_14.setItemText(15, QCoreApplication.translate("Dialog", u"2035", None))

        self.comboBox_12.setItemText(0, QCoreApplication.translate("Dialog", u"1.Yaz Staj\u0131 -10. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(1, QCoreApplication.translate("Dialog", u"2.Yaz Staj\u0131 -11. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(2, QCoreApplication.translate("Dialog", u"3.Ara Donem Staj - 10. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(3, QCoreApplication.translate("Dialog", u"4.Ara D\u00f6nem Staj - 11. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(4, QCoreApplication.translate("Dialog", u"10.S\u0131n\u0131f Eksik Staj", None))
        self.comboBox_12.setItemText(5, QCoreApplication.translate("Dialog", u"11.S\u0131n\u0131f Eksik Staj", None))
        self.comboBox_12.setItemText(6, QCoreApplication.translate("Dialog", u"Di\u011fer - Eksik Staj", None))

        self.label.setText(QCoreApplication.translate("Dialog", u"Aranacak Kelime", None))
        self.label_96.setText(QCoreApplication.translate("Dialog", u"Staj D\u00f6nemi", None))
        self.label_79.setText(QCoreApplication.translate("Dialog", u"Staj Turu", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"\u00d6\u011frenci Ad\u0131", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"\u00d6\u011frenci Soyad\u0131", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Dialog", u"\u00d6\u011frenci No", None))

        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Sorgula", None))
        self.groupBox_37.setTitle(QCoreApplication.translate("Dialog", u"Profil Resmi", None))
        self.label_152.setText("")
        self.groupBox_35.setTitle(QCoreApplication.translate("Dialog", u"Firma Bilgileri", None))
        self.lineEdit_95.setText("")
        self.lineEdit_95.setPlaceholderText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.label_146.setText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.lineEdit_98.setText("")
        self.lineEdit_98.setPlaceholderText(QCoreApplication.translate("Dialog", u"Donem", None))
        self.label_149.setText(QCoreApplication.translate("Dialog", u"Staj D\u00f6nemi", None))
        self.label_151.setText(QCoreApplication.translate("Dialog", u"Staj Turu", None))
        self.lineEdit_99.setText("")
        self.lineEdit_99.setPlaceholderText(QCoreApplication.translate("Dialog", u"Staj Turu", None))
        self.label_150.setText(QCoreApplication.translate("Dialog", u"Staj Kay\u0131t No", None))
        self.lineEdit_36.setPlaceholderText(QCoreApplication.translate("Dialog", u"ID degeri", None))
        self.groupBox_38.setTitle(QCoreApplication.translate("Dialog", u"Ogrenci  Bilgileri", None))
        self.label_153.setText(QCoreApplication.translate("Dialog", u"Ad\u0131", None))
        self.lineEdit_103.setText("")
        self.lineEdit_103.setPlaceholderText(QCoreApplication.translate("Dialog", u"\u00d6\u011frenci Soyad\u0131", None))
        self.lineEdit_104.setText("")
        self.lineEdit_104.setPlaceholderText(QCoreApplication.translate("Dialog", u"\u00d6\u011frenci Ad\u0131 girin", None))
        self.label_154.setText(QCoreApplication.translate("Dialog", u"Soyad\u0131", None))
        self.label_155.setText(QCoreApplication.translate("Dialog", u"Okul No", None))
        self.lineEdit_105.setPlaceholderText(QCoreApplication.translate("Dialog", u"OkulNO", None))
        self.lineEdit_106.setPlaceholderText(QCoreApplication.translate("Dialog", u"Bolum", None))
        self.label_156.setText(QCoreApplication.translate("Dialog", u"Bolum", None))
        self.label_157.setText(QCoreApplication.translate("Dialog", u"/", None))
        self.lineEdit_107.setPlaceholderText(QCoreApplication.translate("Dialog", u"Seviye", None))
        self.lineEdit_108.setPlaceholderText(QCoreApplication.translate("Dialog", u"Sube", None))
        self.label_158.setText(QCoreApplication.translate("Dialog", u"S\u0131n\u0131f", None))
        self.textEdit_10.setMarkdown("")
        self.textEdit_10.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textEdit_10.setPlaceholderText(QCoreApplication.translate("Dialog", u"Notlar", None))
    # retranslateUi

