# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Login.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

import icons_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.setWindowModality(Qt.WindowModal)
        Dialog.resize(525, 452)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(202, 226, 239, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        Dialog.setPalette(palette)
        Dialog.setModal(True)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 501, 69))
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QFrame.WinPanel)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(20, 90, 491, 341))
        self.tabWidget.setAutoFillBackground(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_3 = QPushButton(self.tab)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QRect(10, 20, 121, 111))
        icon = QIcon()
        icon.addFile(u":/staticfiles/icons/managment3.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/staticfiles/icons/managment3.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QSize(100, 100))
        self.pushButton_3.setAutoDefault(True)
        self.pushButton_3.setFlat(True)
        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(48, 150, 331, 99))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.pushButton_2 = QPushButton(self.frame_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(220, 20, 101, 60))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.pushButton_2.setFont(font1)
        self.pushButton = QPushButton(self.frame_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(50, 20, 101, 60))
        self.pushButton.setFont(font1)
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QRect(49, 260, 301, 30))
        font2 = QFont()
        font2.setFamily(u"Segoe UI")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(75)
        self.label_4.setFont(font2)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.frame = QFrame(self.tab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(89, 20, 331, 111))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 20, 130, 30))
        self.label.setFont(font2)
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_2 = QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(180, 60, 140, 30))
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(180, 20, 140, 30))
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 60, 110, 30))
        self.label_2.setFont(font2)
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_4 = QPushButton(self.tab)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(390, 280, 93, 30))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_42 = QGroupBox(self.tab_2)
        self.groupBox_42.setObjectName(u"groupBox_42")
        self.groupBox_42.setGeometry(QRect(20, 10, 351, 321))
        self.lineEdit_114 = QLineEdit(self.groupBox_42)
        self.lineEdit_114.setObjectName(u"lineEdit_114")
        self.lineEdit_114.setGeometry(QRect(140, 40, 200, 30))
        self.lineEdit_120 = QLineEdit(self.groupBox_42)
        self.lineEdit_120.setObjectName(u"lineEdit_120")
        self.lineEdit_120.setGeometry(QRect(140, 120, 200, 30))
        self.label_178 = QLabel(self.groupBox_42)
        self.label_178.setObjectName(u"label_178")
        self.label_178.setGeometry(QRect(270, 260, 21, 20))
        self.label_178.setPixmap(QPixmap(u":/staticfiles/icons/warning.png"))
        self.label_178.setScaledContents(True)
        self.label_179 = QLabel(self.groupBox_42)
        self.label_179.setObjectName(u"label_179")
        self.label_179.setGeometry(QRect(250, 260, 21, 20))
        self.label_179.setPixmap(QPixmap(u":/staticfiles/icons/checked.png"))
        self.label_179.setScaledContents(True)
        self.lineEdit_121 = QLineEdit(self.groupBox_42)
        self.lineEdit_121.setObjectName(u"lineEdit_121")
        self.lineEdit_121.setGeometry(QRect(140, 160, 200, 30))
        self.lineEdit_119 = QLineEdit(self.groupBox_42)
        self.lineEdit_119.setObjectName(u"lineEdit_119")
        self.lineEdit_119.setGeometry(QRect(140, 80, 81, 30))
        self.lineEdit_122 = QLineEdit(self.groupBox_42)
        self.lineEdit_122.setObjectName(u"lineEdit_122")
        self.lineEdit_122.setGeometry(QRect(140, 210, 131, 30))
        self.lineEdit_122.setEchoMode(QLineEdit.Password)
        self.pushButton_61 = QPushButton(self.groupBox_42)
        self.pushButton_61.setObjectName(u"pushButton_61")
        self.pushButton_61.setGeometry(QRect(140, 250, 101, 41))
        self.label_177 = QLabel(self.groupBox_42)
        self.label_177.setObjectName(u"label_177")
        self.label_177.setGeometry(QRect(40, 210, 81, 30))
        self.label_168 = QLabel(self.groupBox_42)
        self.label_168.setObjectName(u"label_168")
        self.label_168.setGeometry(QRect(40, 40, 81, 30))
        self.label_171 = QLabel(self.groupBox_42)
        self.label_171.setObjectName(u"label_171")
        self.label_171.setGeometry(QRect(40, 120, 81, 30))
        self.label_172 = QLabel(self.groupBox_42)
        self.label_172.setObjectName(u"label_172")
        self.label_172.setGeometry(QRect(40, 160, 81, 30))
        self.label_170 = QLabel(self.groupBox_42)
        self.label_170.setObjectName(u"label_170")
        self.label_170.setGeometry(QRect(40, 80, 81, 30))
        self.pushButton_5 = QPushButton(self.tab_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(0, 280, 93, 30))
        self.tabWidget.addTab(self.tab_2, "")
        QWidget.setTabOrder(self.lineEdit, self.lineEdit_2)
        QWidget.setTabOrder(self.lineEdit_2, self.pushButton)
        QWidget.setTabOrder(self.pushButton, self.pushButton_2)
        QWidget.setTabOrder(self.pushButton_2, self.pushButton_4)
        QWidget.setTabOrder(self.pushButton_4, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.lineEdit_114)
        QWidget.setTabOrder(self.lineEdit_114, self.lineEdit_120)
        QWidget.setTabOrder(self.lineEdit_120, self.lineEdit_121)
        QWidget.setTabOrder(self.lineEdit_121, self.lineEdit_119)
        QWidget.setTabOrder(self.lineEdit_119, self.lineEdit_122)
        QWidget.setTabOrder(self.lineEdit_122, self.pushButton_61)
        QWidget.setTabOrder(self.pushButton_61, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.pushButton_5)

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Kullan\u0131c\u0131 Girisi", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\u00d6\u011frenci Y\u00f6netim Sistemi", None))
        self.pushButton_3.setText("")
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"IPTAL", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Giris", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><br/></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Kullan\u0131c\u0131 Ad\u0131", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Sifre", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"DB Ayarlar >", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Tab 1", None))
        self.groupBox_42.setTitle(QCoreApplication.translate("Dialog", u"DataBase Ayarlar\u0131", None))
        self.lineEdit_114.setText(QCoreApplication.translate("Dialog", u"localhost", None))
        self.lineEdit_120.setText(QCoreApplication.translate("Dialog", u"root", None))
        self.label_178.setText("")
        self.label_179.setText("")
        self.lineEdit_121.setText(QCoreApplication.translate("Dialog", u"shool_db", None))
        self.lineEdit_119.setText(QCoreApplication.translate("Dialog", u"3306", None))
        self.lineEdit_122.setText(QCoreApplication.translate("Dialog", u"1234567890", None))
        self.pushButton_61.setText(QCoreApplication.translate("Dialog", u"Test", None))
        self.label_177.setText(QCoreApplication.translate("Dialog", u"\u015eifre :", None))
        self.label_168.setText(QCoreApplication.translate("Dialog", u"Host Ad\u0131:", None))
        self.label_171.setText(QCoreApplication.translate("Dialog", u"Kullan\u0131c\u0131 Ad\u0131:", None))
        self.label_172.setText(QCoreApplication.translate("Dialog", u"Database Ad\u0131:", None))
        self.label_170.setText(QCoreApplication.translate("Dialog", u"Port :", None))
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"< Login", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Tab 2", None))
    # retranslateUi

