# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'quota.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1299, 826)
        self.groupBox_23 = QGroupBox(Dialog)
        self.groupBox_23.setObjectName(u"groupBox_23")
        self.groupBox_23.setGeometry(QRect(10, 10, 571, 201))
        self.label_84 = QLabel(self.groupBox_23)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(-1, 65, 51, 30))
        self.label_84.setMidLineWidth(0)
        self.label_84.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_69 = QLineEdit(self.groupBox_23)
        self.lineEdit_69.setObjectName(u"lineEdit_69")
        self.lineEdit_69.setEnabled(False)
        self.lineEdit_69.setGeometry(QRect(70, 30, 341, 31))
        self.label_86 = QLabel(self.groupBox_23)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(0, 30, 61, 30))
        self.label_86.setMidLineWidth(0)
        self.label_86.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_71 = QLineEdit(self.groupBox_23)
        self.lineEdit_71.setObjectName(u"lineEdit_71")
        self.lineEdit_71.setEnabled(False)
        self.lineEdit_71.setGeometry(QRect(70, 65, 111, 31))
        self.label_81 = QLabel(self.groupBox_23)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(20, 90, 41, 30))
        self.label_81.setMidLineWidth(0)
        self.label_81.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.textEdit_6 = QTextEdit(self.groupBox_23)
        self.textEdit_6.setObjectName(u"textEdit_6")
        self.textEdit_6.setEnabled(False)
        self.textEdit_6.setGeometry(QRect(20, 120, 241, 61))
        self.lineEdit_80 = QLineEdit(self.groupBox_23)
        self.lineEdit_80.setObjectName(u"lineEdit_80")
        self.lineEdit_80.setEnabled(False)
        self.lineEdit_80.setGeometry(QRect(480, 70, 91, 31))
        self.label_94 = QLabel(self.groupBox_23)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(220, 70, 81, 30))
        self.label_94.setMidLineWidth(0)
        self.label_94.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_79 = QLineEdit(self.groupBox_23)
        self.lineEdit_79.setObjectName(u"lineEdit_79")
        self.lineEdit_79.setEnabled(False)
        self.lineEdit_79.setGeometry(QRect(310, 70, 91, 31))
        self.label_95 = QLabel(self.groupBox_23)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(400, 70, 81, 30))
        self.label_95.setMidLineWidth(0)
        self.label_95.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_77 = QLineEdit(self.groupBox_23)
        self.lineEdit_77.setObjectName(u"lineEdit_77")
        self.lineEdit_77.setEnabled(False)
        self.lineEdit_77.setGeometry(QRect(340, 150, 71, 31))
        self.label_93 = QLabel(self.groupBox_23)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(330, 120, 81, 30))
        self.label_93.setMidLineWidth(0)
        self.label_93.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_97 = QLabel(self.groupBox_23)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(460, 120, 101, 30))
        self.label_97.setMidLineWidth(0)
        self.label_97.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_81 = QLineEdit(self.groupBox_23)
        self.lineEdit_81.setObjectName(u"lineEdit_81")
        self.lineEdit_81.setEnabled(False)
        self.lineEdit_81.setGeometry(QRect(480, 150, 71, 31))
        self.label_32 = QLabel(self.groupBox_23)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setEnabled(True)
        self.label_32.setGeometry(QRect(419, 30, 51, 30))
        self.label_32.setMidLineWidth(0)
        self.label_32.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_25 = QLineEdit(self.groupBox_23)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setEnabled(False)
        self.lineEdit_25.setGeometry(QRect(490, 30, 71, 31))
        self.tableWidget_7 = QTableWidget(Dialog)
        if (self.tableWidget_7.columnCount() < 8):
            self.tableWidget_7.setColumnCount(8)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        self.tableWidget_7.setObjectName(u"tableWidget_7")
        self.tableWidget_7.setGeometry(QRect(10, 300, 1271, 391))
        self.tableWidget_7.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_7.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_7.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_7.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_7.setSortingEnabled(True)
        self.tableWidget_7.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_7.horizontalHeader().setDefaultSectionSize(85)
        self.tableWidget_7.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableWidget_7.horizontalHeader().setStretchLastSection(True)
        self.groupBox_27 = QGroupBox(Dialog)
        self.groupBox_27.setObjectName(u"groupBox_27")
        self.groupBox_27.setGeometry(QRect(1060, 60, 211, 131))
        self.pushButton_2 = QPushButton(self.groupBox_27)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(110, 50, 91, 50))
        self.pushButton = QPushButton(self.groupBox_27)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 50, 91, 50))
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(590, 10, 461, 221))
        self.textEdit_8 = QTextEdit(self.groupBox)
        self.textEdit_8.setObjectName(u"textEdit_8")
        self.textEdit_8.setEnabled(False)
        self.textEdit_8.setGeometry(QRect(240, 30, 211, 61))
        self.textEdit_9 = QTextEdit(self.groupBox)
        self.textEdit_9.setObjectName(u"textEdit_9")
        self.textEdit_9.setEnabled(False)
        self.textEdit_9.setGeometry(QRect(20, 100, 431, 111))
        self.label_98 = QLabel(self.groupBox)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(150, 20, 81, 30))
        self.label_98.setMidLineWidth(0)
        self.label_98.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_99 = QLabel(self.groupBox)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(10, 70, 111, 30))
        self.label_99.setMidLineWidth(0)
        self.label_99.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 220, 881, 70))
        self.comboBox_14 = QComboBox(self.groupBox_2)
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.setObjectName(u"comboBox_14")
        self.comboBox_14.setGeometry(QRect(760, 27, 71, 31))
        self.lineEdit = QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(100, 27, 251, 30))
        self.comboBox_12 = QComboBox(self.groupBox_2)
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.setObjectName(u"comboBox_12")
        self.comboBox_12.setGeometry(QRect(530, 27, 151, 31))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 55, 30))
        self.label_96 = QLabel(self.groupBox_2)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(680, 27, 81, 30))
        self.label_96.setMidLineWidth(0)
        self.label_96.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_79 = QLabel(self.groupBox_2)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(460, 30, 61, 30))
        self.label_79.setMidLineWidth(0)
        self.label_79.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.groupBox_23.setTitle(QCoreApplication.translate("Dialog", u"Se\u00e7ilen Firma Bilgileri", None))
        self.label_84.setText(QCoreApplication.translate("Dialog", u"Telefon", None))
        self.lineEdit_69.setText("")
        self.lineEdit_69.setPlaceholderText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.label_86.setText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.lineEdit_71.setText("")
        self.lineEdit_71.setPlaceholderText(QCoreApplication.translate("Dialog", u"Telefon", None))
        self.label_81.setText(QCoreApplication.translate("Dialog", u"Adres", None))
        self.textEdit_6.setPlaceholderText(QCoreApplication.translate("Dialog", u"Adres B\u0130lgileri", None))
        self.lineEdit_80.setText("")
        self.lineEdit_80.setPlaceholderText(QCoreApplication.translate("Dialog", u"Pozisyon", None))
        self.label_94.setText(QCoreApplication.translate("Dialog", u"Firma Yetkili", None))
        self.lineEdit_79.setText("")
        self.lineEdit_79.setPlaceholderText(QCoreApplication.translate("Dialog", u"Firma Yetkilis", None))
        self.label_95.setText(QCoreApplication.translate("Dialog", u"Pozisyonu", None))
        self.lineEdit_77.setText("")
        self.lineEdit_77.setPlaceholderText(QCoreApplication.translate("Dialog", u"K\u0131z say\u0131s\u0131", None))
        self.label_93.setText(QCoreApplication.translate("Dialog", u"Kapasite - K\u0131z", None))
        self.label_97.setText(QCoreApplication.translate("Dialog", u"Kapasite - Erkek", None))
        self.lineEdit_81.setText("")
        self.lineEdit_81.setPlaceholderText(QCoreApplication.translate("Dialog", u"Erkek Say\u0131s\u0131", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Kay\u0131t No", None))
        self.lineEdit_25.setPlaceholderText(QCoreApplication.translate("Dialog", u"ID degeri", None))
        ___qtablewidgetitem = self.tableWidget_7.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"Kay\u0131t No", None));
        ___qtablewidgetitem1 = self.tableWidget_7.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"Donem", None));
        ___qtablewidgetitem2 = self.tableWidget_7.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"Staj Turu", None));
        ___qtablewidgetitem3 = self.tableWidget_7.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None));
        ___qtablewidgetitem4 = self.tableWidget_7.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Dialog", u"K\u0131z Kont.", None));
        ___qtablewidgetitem5 = self.tableWidget_7.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Dialog", u"Erkek Kont", None));
        ___qtablewidgetitem6 = self.tableWidget_7.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Dialog", u"Ogretmen", None));
        ___qtablewidgetitem7 = self.tableWidget_7.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Dialog", u"Ac\u0131klama", None));
        self.groupBox_27.setTitle(QCoreApplication.translate("Dialog", u"Kontrol", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Iptal", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"OK", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Notlar", None))
        self.textEdit_8.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textEdit_8.setPlaceholderText(QCoreApplication.translate("Dialog", u"istenilen yetenekler", None))
        self.label_98.setText(QCoreApplication.translate("Dialog", u"Yetenekler", None))
        self.label_99.setText(QCoreApplication.translate("Dialog", u"G\u00f6r\u00fc\u015fme Raporu", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Filitre", None))
        self.comboBox_14.setItemText(0, QCoreApplication.translate("Dialog", u"2020", None))
        self.comboBox_14.setItemText(1, QCoreApplication.translate("Dialog", u"2021", None))
        self.comboBox_14.setItemText(2, QCoreApplication.translate("Dialog", u"2022", None))
        self.comboBox_14.setItemText(3, QCoreApplication.translate("Dialog", u"2023", None))
        self.comboBox_14.setItemText(4, QCoreApplication.translate("Dialog", u"2024", None))
        self.comboBox_14.setItemText(5, QCoreApplication.translate("Dialog", u"2025", None))
        self.comboBox_14.setItemText(6, QCoreApplication.translate("Dialog", u"2026", None))
        self.comboBox_14.setItemText(7, QCoreApplication.translate("Dialog", u"2027", None))
        self.comboBox_14.setItemText(8, QCoreApplication.translate("Dialog", u"2028", None))
        self.comboBox_14.setItemText(9, QCoreApplication.translate("Dialog", u"2029", None))
        self.comboBox_14.setItemText(10, QCoreApplication.translate("Dialog", u"2030", None))
        self.comboBox_14.setItemText(11, QCoreApplication.translate("Dialog", u"2031", None))
        self.comboBox_14.setItemText(12, QCoreApplication.translate("Dialog", u"2032", None))
        self.comboBox_14.setItemText(13, QCoreApplication.translate("Dialog", u"2033", None))
        self.comboBox_14.setItemText(14, QCoreApplication.translate("Dialog", u"2034", None))
        self.comboBox_14.setItemText(15, QCoreApplication.translate("Dialog", u"2035", None))

        self.comboBox_12.setItemText(0, QCoreApplication.translate("Dialog", u"1.Yaz Staj\u0131 -10. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(1, QCoreApplication.translate("Dialog", u"2.Yaz Staj\u0131 -11. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(2, QCoreApplication.translate("Dialog", u"3.Ara Donem Staj - 10. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(3, QCoreApplication.translate("Dialog", u"4.Ara D\u00f6nem Staj - 11. S\u0131n\u0131f", None))
        self.comboBox_12.setItemText(4, QCoreApplication.translate("Dialog", u"10.S\u0131n\u0131f Eksik Staj", None))
        self.comboBox_12.setItemText(5, QCoreApplication.translate("Dialog", u"11.S\u0131n\u0131f Eksik Staj", None))
        self.comboBox_12.setItemText(6, QCoreApplication.translate("Dialog", u"Di\u011fer - Eksik Staj", None))

        self.label.setText(QCoreApplication.translate("Dialog", u"Firma Ad\u0131", None))
        self.label_96.setText(QCoreApplication.translate("Dialog", u"Staj D\u00f6nemi", None))
        self.label_79.setText(QCoreApplication.translate("Dialog", u"Staj Turu", None))
    # retranslateUi

